# Parameters for run-wann-classification.py with the sklearn digits dataset.

# Machine
num_workers: 1
use_torch: False

# Data
dataset: digits
num_inputs: 64
num_outputs: 10

# Evolution
num_generations: 1024
population_size: 480
tournament_size: 32
batch_size: 500
p_initial_connection_enabled: 0.05
p_change_activation: 0.5
p_add_node: 0.25
p_add_connection: 0.25
elite_ratio: 0.2
cull_ratio: 0.2
test_every: 5
p_complexity_objective: 0.8
num_mutations_per_generation: 1
