# Parameters for run-wann-classification.py with the MNIST dataset.
# As in the WANN paper (Gaier et al. 2019) except where noted.

# Machine
num_workers: 1
use_torch: False

# Data
dataset: mnist
num_inputs: 256
num_outputs: 10

# Evolution
num_generations: 4096
population_size: 960
# Note that we use twice the tournament size as in the WANN paper. Their implementation
# contains a bug that makes it use twice the tournament size given in the paper.
tournament_size: 64
batch_size: 1000
p_initial_connection_enabled: 0.05
p_change_activation: 0.5
p_add_node: 0.25
p_add_connection: 0.25
elite_ratio: 0.2
cull_ratio: 0.2
test_every: 20
p_complexity_objective: 0.8
num_mutations_per_generation: 1
