# Parameters for wlnn-mnist.py with the sklearn digits dataset.

# Machine
use_cuda: False
num_workers: 1

# Dataset
dataset: digits
num_inputs: 64
num_outputs: 10

# Evolution
num_generations: 1024
population_size: 480
tournament_size: 32
p_initial_connection_enabled: 0.05
p_add_node: 0.5
p_add_connection: 0.5
elite_ratio: 0.2
cull_ratio: 0.2
p_complexity_objective: 0.8
num_mutations_per_generation: 1

# Learning
optimizer: adam
learning_rule: backprop
lr: 0.01
batch_size: 256
num_epochs: 3
inherit_weights: False
train_only_outputs: False
