# Parameters for wlnn-mnist-no-evolution.py with backprop on the MNIST dataset.

# Machine
use_cuda: False

# Data
dataset: mnist
num_inputs: 256
num_outputs: 10

# Network
p_initial_connection_enabled: 1

# Learning
learning_rule: feedback_alignment
optimizer: adam
num_epochs: 100
batch_size: 256
lr: 0.01  # 0.005 for sgd, 0.01 for adam, 1 for adadelta (not very optimized)
